### PR TITLE
fixes #182: different types for the same field causes error

### LINKED ISSUE #182: Reading node types / schema creation fails when reading nodes with advanced data types
Use this test record in your Neo4j instance, this is intended to stress the typing system:

```
create (:Types { 
   strA: ["Hello"], 
   inteA: [4], 
   floA: [3.14], 
   boolA: [true], 
   ptA: [point({ latitude: 0, longitude: 0 })], 
   dt: date(), 
   tm: time(), 
   ldt: localdatetime(), 
   dtA: [date()], 
   tmA: [time()], 
   ldtA: [localdatetime()], 
   dt_t: datetime(), 
   lt:localtime(), 
   dur: duration.between(datetime(), date()) 
});
```

Now do this small pyspark program:

```
df = spark.read.format("org.neo4j.spark.DataSource") \
    .option("url", "bolt://neo4j:7687") \
    .option("authentication.basic.username", "neo4j") \
    .option("authentication.basic.password", "zeppelin") \
    .option("query", "MATCH (t:Types) RETURN t") \
    .load()

df.show()
```

Result:

```
Py4JJavaError: An error occurred while calling o284.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 24.0 failed 1 times, most recent failure: Lost task 0.0 in stage 24.0 (TID 24, localhost, executor driver): java.lang.ClassCastException: org.apache.spark.unsafe.types.UTF8String cannot be cast to org.apache.spark.sql.catalyst.InternalRow
	at org.apache.spark.sql.catalyst.util.GenericArrayData.getStruct(GenericArrayData.scala:78)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.project_fieldToString_1_2$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:255)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
```

### PR DESCRIPTION
**Pull request by utnaf**
fixes #182

Say we have 

```
CREATE (p1:Person {age: "32"}), (p2:Person {age: 23})
```

Field has 2 different types and this is a problem.

When APOC is used to find the schema, and more than 1 type is present for the same field, all the values will be casted to String and a Warning message will be displayed saying:

```
The field "age" has different types: [String, Long]
Every value will be casted to string.
```

### CODE REVIEW

**Comment by utnaf** [comment]
Added FAQ and a paragraph to the doc to describe this situation

https://github.com/neo4j-contrib/neo4j-spark-connector/pull/177/commits/7aa77c07b06958c4d8e21169f60b51f5ed0ef665

**Comment by conker84** [comment]
Thank you @utnaf!

**Comment by conker84** [comment]
I think that makes sense add the same behaviour here at line 91:

https://github.com/neo4j-contrib/neo4j-spark-connector/blob/c306470042d68d9885e6bc71eed6778b61e970f9/src/main/scala/org/neo4j/spark/service/SchemaService.scala#L91-L97

**Review by conker84 — APPROVED** [review]
LGTM

**Pull request merged**
