### PR TITLE
Replace hyperlink by linkcheck (fasteeeer)

### PR DESCRIPTION
**Pull request by ggrossetie**
- linkcheck is written in Dart and available as a binary (for macOS, Windows, Linux on x64): https://github.com/filiph/linkcheck
- linkcheck is fast! on my machine it takes less than 1 second to check links
- linkcheck requires a local HTTP server, it can't check links from the filesystem
- While integrating linkcheck, I found two broken links in `doc/docs/modules/ROOT/pages/quickstart.adoc`
- We can configure ignore links using a txt file

I've updated the `doc/tasks/lint-links.js` script to:

- download linkcheck binary (if it does not exists)
- chmod +x
- start the local HTTP server (using `server.js`)
- execute `bin/linkcheck --skip-file ignore-links.txt :port`
- stop server and output result

Here's an example when there are broken links:

```console
$ npm run lint:links

bin/linkcheck already exists, skipping download
📘 http://localhost:8000
bin/linkcheck --skip-file ignore-links.txt :8000
Done crawling.                                    

http://localhost:8000/developer/spark/
- (44:6) => http://localhost:8000/ (HTTP 200)
  - redirect path:
    - http://localhost:8000/ (302)
    - /developer/spark (301)
    - /developer/spark/ (200)
- (44:6) => http://localhost:8000/ (HTTP 200)
  - redirect path:
    - http://localhost:8000/ (302)
    - /developer/spark (301)
    - /developer/spark/ (200)

http://localhost:8000/developer/spark/architecture/
- (44:6) => http://localhost:8000/ (HTTP 200)
  - redirect path:
    - http://localhost:8000/ (302)
    - /developer/spark (301)
    - /developer/spark/ (200)

http://localhost:8000/developer/spark/aura/
- (44:6) => http://localhost:8000/ (HTTP 200)
  - redirect path:
    - http://localhost:8000/ (302)
    - /developer/spark (301)
    - /developer/spark/ (200)

http://localhost:8000/developer/spark/configuration/
- (44:6) => http://localhost:8000/ (HTTP 200)
  - redirect path:
    - http://localhost:8000/ (302)
    - /developer/spark (301)
    - /developer/spark/ (200)

http://localhost:8000/developer/spark/faq/
- (44:6) => http://localhost:8000/ (HTTP 200)
  - redirect path:
    - http://localhost:8000/ (302)
    - /developer/spark (301)
    - /developer/spark/ (200)

http://localhost:8000/developer/spark/gds/
- (44:6) => http://localhost:8000/ (HTTP 200)
  - redirect path:
    - http://localhost:8000/ (302)
    - /developer/spark (301)
    - /developer/spark/ (200)

http://localhost:8000/developer/spark/neo4j-cluster/
- (44:6) => http://localhost:8000/ (HTTP 200)
  - redirect path:
    - http://localhost:8000/ (302)
    - /developer/spark (301)
    - /developer/spark/ (200)

http://localhost:8000/developer/spark/overview/
- (44:6) => http://localhost:8000/ (HTTP 200)
  - redirect path:
    - http://localhost:8000/ (302)
    - /developer/spark (301)
    - /developer/spark/ (200)

http://localhost:8000/developer/spark/python/
- (44:6) => http://localhost:8000/ (HTTP 200)
  - redirect path:
    - http://localhost:8000/ (302)
    - /developer/spark (301)
    - /developer/spark/ (200)

http://localhost:8000/developer/spark/quick-java-example/
- (44:6) => http://localhost:8000/ (HTTP 200)
  - redirect path:
    - http://localhost:8000/ (302)
    - /developer/spark (301)
    - /developer/spark/ (200)

http://localhost:8000/developer/spark/quickstart/
- (44:6) => http://localhost:8000/ (HTTP 200)
  - redirect path:
    - http://localhost:8000/ (302)
    - /developer/spark (301)
    - /developer/spark/ (200)
- (585:13) 'Reading' => http://localhost:8000/developer/spark/quickstart/reading (HTTP 404)

http://localhost:8000/developer/spark/reading/
- (44:6) => http://localhost:8000/ (HTTP 200)
  - redirect path:
    - http://localhost:8000/ (302)
    - /developer/spark (301)
    - /developer/spark/ (200)

http://localhost:8000/developer/spark/types/
- (44:6) => http://localhost:8000/ (HTTP 200)
  - redirect path:
    - http://localhost:8000/ (302)
    - /developer/spark (301)
    - /developer/spark/ (200)

http://localhost:8000/developer/spark/writing/
- (44:6) => http://localhost:8000/ (HTTP 200)
  - redirect path:
    - http://localhost:8000/ (302)
    - /developer/spark (301)
    - /developer/spark/ (200)

Errors. Checked 2086 links, 17 destination URLs (49 ignored), 1 has error(s), 0 have warnings.
```
Yes it's a bit verbose... 

And when everything is fine:

```console
$ npm run lint:links

bin/linkcheck already exists, skipping download
📘 http://localhost:8000
bin/linkcheck --skip-file ignore-links.txt :8000
Perfect. Checked 2086 links, 16 destination URLs (49 ignored).
```

### CODE REVIEW

**Comment by moxious** [comment]
Still WIP

**Comment by fbiville** [comment]
@ggrossetie can we go ahead with this?

**Comment by ggrossetie** [comment]
Sorry for the late reply. I will rebase and fix the build.

**Comment by ali-ince** [comment]
@ggrossetie please re-open it once you have some bandwidth to update the PR.

**Comment by ali-ince** [comment]
and the doc repository is now moved over to https://github.com/neo4j/docs-spark.

**Pull request closed without merging**
